apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-frontend-deployment
  labels:
    app: catalog-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-frontend
  template:
    metadata:
      labels:
        app: catalog-frontend
    spec:
      containers:
      - name: catalog-frontend
        image: chaphe/frontend-catalog-image:1.0
        ports:
        - containerPort: 80
        env:
        - name: REVIEWS_URL
          value: http://10.245.233.25:3000
        - name: STORE_URL
          value: http://10.245.125.225:8082
        - name: CATALOG_URL
          value: http://10.245.216.220:8081
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-frontend-service
spec:
  #type: NodePort
  selector:
    app: catalog-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      #nodePort: 30301
